language: node_js
node_js:
  - "12"

dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run lintbe
  - npm run linthtml
  - npm run lintscss
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadless
  - npm run e2e -- --protractor-config='e2e/protractor.ci.conf.js'
#  - npm run testbe
  - npm run predev
  - npm run build -- --aot --prod
