name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.4.10
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadless
    - run: npm run e2e -- --protractor-config='e2e/protractor.ci.conf.js'
    - run: npm run testbe