name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.4.10
        ports:
          - 27017:27017
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadless
    - run: npm run testbe